INSERT INTO movie (id, title, ranking) values (1, 'Um Sonho de Liberdade (1994)', '9.2');
INSERT INTO movie (id, title, ranking) values (2, 'O Poderoso Chefão (1972)', '9.2');
INSERT INTO movie (id, title, ranking) values (3, 'Batman: O Cavaleiro das Trevas (2008)', '9.0');
INSERT INTO movie (id, title, ranking) values (4, 'O Poderoso Chefão II (1974)', '9.0');
INSERT INTO movie (id, title, ranking) values (5, '12 Homens e uma Sentença (1957)', '8.9');
INSERT INTO movie (id, title, ranking) values (6, 'A Lista de Schindler (1993)', '8.9');
INSERT INTO movie (id, title, ranking) values (7, 'O Senhor dos Anéis: O Retorno do Rei (2003)', '8.9');
INSERT INTO movie (id, title, ranking) values (8, 'Pulp Fiction: Tempo de Violência (1994)', '8.8');
INSERT INTO movie (id, title, ranking) values (9, 'O Senhor dos Anéis: A Sociedade do Anel (2001)', '8.8');
INSERT INTO movie (id, title, ranking) values (10, 'Três Homens em Conflito (1966)', '8.8');
INSERT INTO movie (id, title, ranking) values (11, 'Forrest Gump: O Contador de Histórias (1994)', '8.8');
INSERT INTO movie (id, title, ranking) values (12, 'Clube da Luta (1999)', '8.7');
INSERT INTO movie (id, title, ranking) values (13, 'A Origem (2010)', '8.7');
INSERT INTO movie (id, title, ranking) values (14, 'O Senhor dos Anéis: As Duas Torres (2002)', '8.7');
INSERT INTO movie (id, title, ranking) values (15, 'O Império Contra-Ataca (1980)', '8.7');
INSERT INTO movie (id, title, ranking) values (16, 'Matrix (1999)', '8.7');
INSERT INTO movie (id, title, ranking) values (17, 'Os Bons Companheiros (1990)', '8.7');
INSERT INTO movie (id, title, ranking) values (18, 'Um Estranho no Ninho (1975)', '8.6');
INSERT INTO movie (id, title, ranking) values (19, 'Seven: Os Sete Crimes Capitais (1995)', '8.6');
INSERT INTO movie (id, title, ranking) values (20, 'Os Sete Samurais (1954)', '8.6');
INSERT INTO movie (id, title, ranking) values (21, 'A Felicidade Não se Compra (1946)', '8.6');
INSERT INTO movie (id, title, ranking) values (22, 'O Silêncio dos Inocentes (1991)', '8.6');
INSERT INTO movie (id, title, ranking) values (23, 'Cidade de Deus (2002)', '8.6');
INSERT INTO movie (id, title, ranking) values (24, 'O Resgate do Soldado Ryan (1998)', '8.6');
INSERT INTO movie (id, title, ranking) values (25, 'A Vida é Bela (1997)', '8.6');
INSERT INTO movie (id, title, ranking) values (26, 'À Espera de um Milagre (1999)', '8.6');
INSERT INTO movie (id, title, ranking) values (27, 'Interestelar (2014)', '8.6');
INSERT INTO movie (id, title, ranking) values (28, 'Guerra nas Estrelas (1977)', '8.6');
INSERT INTO movie (id, title, ranking) values (29, 'O Exterminador do Futuro 2 - O Julgamento Final (1991)', '8.5');
INSERT INTO movie (id, title, ranking) values (30, 'De Volta para o Futuro (1985)', '8.5');
INSERT INTO movie (id, title, ranking) values (31, 'A Viagem de Chihiro (2001)', '8.5');
INSERT INTO movie (id, title, ranking) values (32, 'Psicose (1960)', '8.5');
INSERT INTO movie (id, title, ranking) values (33, 'O Pianista (2002)', '8.5');
INSERT INTO movie (id, title, ranking) values (34, 'O Profissional (1994)', '8.5');
INSERT INTO movie (id, title, ranking) values (35, 'Parasita (2019)', '8.5');
INSERT INTO movie (id, title, ranking) values (36, 'O Rei Leão (1994)', '8.5');
INSERT INTO movie (id, title, ranking) values (37, 'Gladiador (2000)', '8.5');
INSERT INTO movie (id, title, ranking) values (38, 'A Outra História Americana (1998)', '8.5');
INSERT INTO movie (id, title, ranking) values (39, 'Os Infiltrados (2006)', '8.5');
INSERT INTO movie (id, title, ranking) values (40, 'Os Suspeitos (1995)', '8.5');
INSERT INTO movie (id, title, ranking) values (41, 'O Grande Truque (2006)', '8.5');
INSERT INTO movie (id, title, ranking) values (42, 'Casablanca (1942)', '8.5');
INSERT INTO movie (id, title, ranking) values (43, 'Whiplash: Em Busca da Perfeição (2014)', '8.5');
INSERT INTO movie (id, title, ranking) values (44, 'Intocáveis (2011)', '8.5');
INSERT INTO movie (id, title, ranking) values (45, 'Harakiri (1962)', '8.5');
INSERT INTO movie (id, title, ranking) values (46, 'Túmulo dos Vagalumes (1988)', '8.5');
INSERT INTO movie (id, title, ranking) values (47, 'Tempos Modernos (1936)', '8.4');
INSERT INTO movie (id, title, ranking) values (48, 'Era uma Vez no Oeste (1968)', '8.4');
INSERT INTO movie (id, title, ranking) values (49, 'Top Gun: Maverick (2022)', '8.4');
INSERT INTO movie (id, title, ranking) values (50, 'Janela Indiscreta (1954)', '8.4');
INSERT INTO movie (id, title, ranking) values (51, 'Alien - O 8º Passageiro (1979)', '8.4');
INSERT INTO movie (id, title, ranking) values (52, 'Luzes da Cidade (1931)', '8.4');
INSERT INTO movie (id, title, ranking) values (53, 'Cinema Paradiso (1988)', '8.4');
INSERT INTO movie (id, title, ranking) values (54, 'Apocalypse Now (1979)', '8.4');
INSERT INTO movie (id, title, ranking) values (55, 'Amnésia (2000)', '8.4');
INSERT INTO movie (id, title, ranking) values (56, 'Os Caçadores da Arca Perdida (1981)', '8.4');
INSERT INTO movie (id, title, ranking) values (57, 'Django Livre (2012)', '8.4');
INSERT INTO movie (id, title, ranking) values (58, 'WALL·E (2008)', '8.4');
INSERT INTO movie (id, title, ranking) values (59, 'A Vida dos Outros (2006)', '8.4');
INSERT INTO movie (id, title, ranking) values (60, 'Crepúsculo dos Deuses (1950)', '8.4');
INSERT INTO movie (id, title, ranking) values (61, 'Glória Feita de Sangue (1957)', '8.4');
INSERT INTO movie (id, title, ranking) values (62, 'O Iluminado (1980)', '8.4');
INSERT INTO movie (id, title, ranking) values (63, 'O Grande Ditador (1940)', '8.4');
INSERT INTO movie (id, title, ranking) values (64, 'Testemunha de Acusação (1957)', '8.4');
INSERT INTO movie (id, title, ranking) values (65, 'Vingadores: Guerra Infinita (2018)', '8.4');
INSERT INTO movie (id, title, ranking) values (66, 'Aliens, O Resgate (1986)', '8.3');
INSERT INTO movie (id, title, ranking) values (67, 'Beleza Americana (1999)', '8.3');
INSERT INTO movie (id, title, ranking) values (68, 'Dr. Fantástico (1964)', '8.3');
INSERT INTO movie (id, title, ranking) values (69, 'Homem-Aranha no Aranhaverso (2018)', '8.3');
INSERT INTO movie (id, title, ranking) values (70, 'Batman: O Cavaleiro das Trevas Ressurge (2012)', '8.3');
INSERT INTO movie (id, title, ranking) values (71, 'Oldboy (2003)', '8.3');
INSERT INTO movie (id, title, ranking) values (72, 'Coringa (2019)', '8.3');
INSERT INTO movie (id, title, ranking) values (73, 'Amadeus (1984)', '8.3');
INSERT INTO movie (id, title, ranking) values (74, 'Coração Valente (1995)', '8.3');
INSERT INTO movie (id, title, ranking) values (75, 'Toy Story (1995)', '8.3');
INSERT INTO movie (id, title, ranking) values (76, 'Viva: A Vida é uma Festa (2017)', '8.3');
INSERT INTO movie (id, title, ranking) values (77, 'O Barco: Inferno no Mar (1981)', '8.3');
INSERT INTO movie (id, title, ranking) values (78, 'Bastardos Inglórios (2009)', '8.3');
INSERT INTO movie (id, title, ranking) values (79, 'Princesa Mononoke (1997)', '8.3');
INSERT INTO movie (id, title, ranking) values (80, 'Vingadores: Ultimato (2019)', '8.3');
INSERT INTO movie (id, title, ranking) values (81, 'Era uma Vez na América (1984)', '8.3');
INSERT INTO movie (id, title, ranking) values (82, 'Gênio Indomável (1997)', '8.3');
INSERT INTO movie (id, title, ranking) values (83, 'Your Name. (2016)', '8.3');
INSERT INTO movie (id, title, ranking) values (84, 'Toy Story 3 (2010)', '8.3');
INSERT INTO movie (id, title, ranking) values (85, 'Réquiem para um Sonho (2000)', '8.3');
INSERT INTO movie (id, title, ranking) values (86, 'Cantando na Chuva (1952)', '8.3');
INSERT INTO movie (id, title, ranking) values (87, '3 Idiotas (2009)', '8.3');
INSERT INTO movie (id, title, ranking) values (88, 'Star Wars, Episódio VI: O Retorno do Jedi (1983)', '8.3');
INSERT INTO movie (id, title, ranking) values (89, 'Céu E Inferno (1963)', '8.3');
INSERT INTO movie (id, title, ranking) values (90, '2001: Uma Odisséia no Espaço (1968)', '8.3');
INSERT INTO movie (id, title, ranking) values (91, 'Brilho Eterno de uma Mente sem Lembranças (2004)', '8.3');
INSERT INTO movie (id, title, ranking) values (92, 'Cães de Aluguel (1992)', '8.3');
INSERT INTO movie (id, title, ranking) values (93, 'Cafarnaum (2018)', '8.3');
INSERT INTO movie (id, title, ranking) values (94, 'Cidadão Kane (1941)', '8.3');
INSERT INTO movie (id, title, ranking) values (95, 'Lawrence da Arábia (1962)', '8.3');
INSERT INTO movie (id, title, ranking) values (96, 'A Caça (2012)', '8.3');
INSERT INTO movie (id, title, ranking) values (97, 'M, o Vampiro de Dusseldorf (1931)', '8.3');
INSERT INTO movie (id, title, ranking) values (98, 'Intriga Internacional (1959)', '8.3');
INSERT INTO movie (id, title, ranking) values (99, 'Um Corpo que Cai (1958)', '8.2');
INSERT INTO movie (id, title, ranking) values (100, 'Vá e Veja (1985)', '8.2');
INSERT INTO movie (id, title, ranking) values (101, 'O Fabuloso Destino de Amélie Poulain (2001)', '8.2');
INSERT INTO movie (id, title, ranking) values (102, 'Laranja Mecânica (1971)', '8.2');
INSERT INTO movie (id, title, ranking) values (103, 'Pacto de Sangue (1944)', '8.2');
INSERT INTO movie (id, title, ranking) values (104, 'Nascido para Matar (1987)', '8.2');
INSERT INTO movie (id, title, ranking) values (105, 'Se Meu Apartamento Falasse (1960)', '8.2');
INSERT INTO movie (id, title, ranking) values (106, 'Scarface (1983)', '8.2');
INSERT INTO movie (id, title, ranking) values (107, 'Viver (1952)', '8.2');
INSERT INTO movie (id, title, ranking) values (108, 'Golpe de Mestre (1973)', '8.2');
INSERT INTO movie (id, title, ranking) values (109, 'O Sol é para Todos (1962)', '8.2');
INSERT INTO movie (id, title, ranking) values (110, 'Taxi Driver: Motorista de Táxi (1976)', '8.2');
INSERT INTO movie (id, title, ranking) values (111, 'Up: Altas Aventuras (2009)', '8.2');
INSERT INTO movie (id, title, ranking) values (112, 'Fogo Contra Fogo (1995)', '8.2');
INSERT INTO movie (id, title, ranking) values (113, 'Los Angeles: Cidade Proibida (1997)', '8.2');
INSERT INTO movie (id, title, ranking) values (114, 'Metrópolis (1927)', '8.2');
INSERT INTO movie (id, title, ranking) values (115, 'A Separação (2011)', '8.2');
INSERT INTO movie (id, title, ranking) values (116, 'Incêndios (2010)', '8.2');
INSERT INTO movie (id, title, ranking) values (117, 'Duro de Matar (1988)', '8.2');
INSERT INTO movie (id, title, ranking) values (118, 'Snatch: Porcos e Diamantes (2000)', '8.2');
INSERT INTO movie (id, title, ranking) values (119, 'Indiana Jones e a Última Cruzada (1989)', '8.2');
INSERT INTO movie (id, title, ranking) values (120, 'Ladrões de Bicicletas (1948)', '8.2');
INSERT INTO movie (id, title, ranking) values (121, 'Hamilton (2020)', '8.2');
INSERT INTO movie (id, title, ranking) values (122, '1917 (2019)', '8.2');
INSERT INTO movie (id, title, ranking) values (123, 'Como Estrelas na Terra (2007)', '8.2');
INSERT INTO movie (id, title, ranking) values (124, 'A Queda! As Últimas Horas de Hitler (2004)', '8.2');
INSERT INTO movie (id, title, ranking) values (125, 'Por uns Dólares a Mais (1965)', '8.2');
INSERT INTO movie (id, title, ranking) values (126, 'Batman Begins (2005)', '8.2');
INSERT INTO movie (id, title, ranking) values (127, 'Dangal (2016)', '8.2');
INSERT INTO movie (id, title, ranking) values (128, 'O Garoto (1921)', '8.2');
INSERT INTO movie (id, title, ranking) values (129, 'Quanto Mais Quente Melhor (1959)', '8.2');
INSERT INTO movie (id, title, ranking) values (130, 'A Malvada (1950)', '8.2');
INSERT INTO movie (id, title, ranking) values (131, 'Meu Pai (2020)', '8.2');
INSERT INTO movie (id, title, ranking) values (132, 'Homem-Aranha: Sem Volta para Casa (2021)', '8.2');
INSERT INTO movie (id, title, ranking) values (133, 'Green Book: O Guia (2018)', '8.2');
INSERT INTO movie (id, title, ranking) values (134, 'O Lobo de Wall Street (2013)', '8.2');
INSERT INTO movie (id, title, ranking) values (135, 'Julgamento em Nuremberg (1961)', '8.2');
INSERT INTO movie (id, title, ranking) values (136, 'Ran (1985)', '8.2');
INSERT INTO movie (id, title, ranking) values (137, 'Cassino (1995)', '8.2');
INSERT INTO movie (id, title, ranking) values (138, 'Os Imperdoáveis (1992)', '8.2');
INSERT INTO movie (id, title, ranking) values (139, 'O Labirinto do Fauno (2006)', '8.2');
INSERT INTO movie (id, title, ranking) values (140, 'Sangue Negro (2007)', '8.2');
INSERT INTO movie (id, title, ranking) values (141, 'O Sexto Sentido (1999)', '8.2');
INSERT INTO movie (id, title, ranking) values (142, 'O Show de Truman: O Show da Vida (1998)', '8.2');
INSERT INTO movie (id, title, ranking) values (143, 'Uma Mente Brilhante (2001)', '8.2');
INSERT INTO movie (id, title, ranking) values (144, 'Monty Python em Busca do Cálice Sagrado (1975)', '8.2');
INSERT INTO movie (id, title, ranking) values (145, 'Yojimbo, o Guarda-Costas (1961)', '8.2');
INSERT INTO movie (id, title, ranking) values (146, 'O Tesouro da Sierra Madre (1948)', '8.1');
INSERT INTO movie (id, title, ranking) values (147, 'Ilha do Medo (2010)', '8.1');
INSERT INTO movie (id, title, ranking) values (148, 'Jurassic Park (1993)', '8.1');
INSERT INTO movie (id, title, ranking) values (149, 'Fugindo do Inferno (1963)', '8.1');
INSERT INTO movie (id, title, ranking) values (150, 'Rashomon (1950)', '8.1');
INSERT INTO movie (id, title, ranking) values (151, 'Kill Bill: Volume 1 (2003)', '8.1');
INSERT INTO movie (id, title, ranking) values (152, 'Onde os Fracos Não Têm Vez (2007)', '8.1');
INSERT INTO movie (id, title, ranking) values (153, 'Procurando Nemo (2003)', '8.1');
INSERT INTO movie (id, title, ranking) values (154, 'O Homem Elefante (1980)', '8.1');
INSERT INTO movie (id, title, ranking) values (155, 'Chinatown (1974)', '8.1');
INSERT INTO movie (id, title, ranking) values (156, 'Touro Indomável (1980)', '8.1');
INSERT INTO movie (id, title, ranking) values (157, 'O Enigma de Outro Mundo (1982)', '8.1');
INSERT INTO movie (id, title, ranking) values (158, '...E o Vento Levou (1939)', '8.1');
INSERT INTO movie (id, title, ranking) values (159, 'V de Vingança (2006)', '8.1');
INSERT INTO movie (id, title, ranking) values (160, 'Divertida Mente (2015)', '8.1');
INSERT INTO movie (id, title, ranking) values (161, 'Jogos, Trapaças e Dois Canos Fumegantes (1998)', '8.1');
INSERT INTO movie (id, title, ranking) values (162, 'Disque M para Matar (1954)', '8.1');
INSERT INTO movie (id, title, ranking) values (163, 'O Segredo dos Seus Olhos (2009)', '8.1');
INSERT INTO movie (id, title, ranking) values (164, 'O Castelo Animado (2004)', '8.1');
INSERT INTO movie (id, title, ranking) values (165, 'A Ponte do Rio Kwai (1957)', '8.1');
INSERT INTO movie (id, title, ranking) values (166, 'Três Anúncios para um Crime (2017)', '8.1');
INSERT INTO movie (id, title, ranking) values (167, 'Trainspotting: Sem Limites (1996)', '8.1');
INSERT INTO movie (id, title, ranking) values (168, 'Guerreiro (2011)', '8.1');
INSERT INTO movie (id, title, ranking) values (169, 'Gran Torino (2008)', '8.1');
INSERT INTO movie (id, title, ranking) values (170, 'Fargo: Uma Comédia de Erros (1996)', '8.1');
INSERT INTO movie (id, title, ranking) values (171, 'Os Suspeitos (2013)', '8.1');
INSERT INTO movie (id, title, ranking) values (172, 'Meu Amigo Totoro (1988)', '8.1');
INSERT INTO movie (id, title, ranking) values (173, 'Tudo em Todo Lugar ao Mesmo Tempo (2022)', '8.1');
INSERT INTO movie (id, title, ranking) values (174, 'Menina de Ouro (2004)', '8.1');
INSERT INTO movie (id, title, ranking) values (175, 'Em Busca do Ouro (1925)', '8.1');
INSERT INTO movie (id, title, ranking) values (176, 'Prenda-me se for Capaz (2002)', '8.1');
INSERT INTO movie (id, title, ranking) values (177, 'Blade Runner: O Caçador de Androides (1982)', '8.1');
INSERT INTO movie (id, title, ranking) values (178, 'Sindicato de Ladrões (1954)', '8.1');
INSERT INTO movie (id, title, ranking) values (179, 'Filhos do Paraíso (1997)', '8.1');
INSERT INTO movie (id, title, ranking) values (180, 'O 3º Homem (1949)', '8.1');
INSERT INTO movie (id, title, ranking) values (181, 'Ben-Hur (1959)', '8.1');
INSERT INTO movie (id, title, ranking) values (182, 'Antes do Amanhecer (1995)', '8.1');
INSERT INTO movie (id, title, ranking) values (183, '12 Anos de Escravidão (2013)', '8.1');
INSERT INTO movie (id, title, ranking) values (184, 'Morangos Silvestres (1957)', '8.1');
INSERT INTO movie (id, title, ranking) values (185, 'A General (1926)', '8.1');
INSERT INTO movie (id, title, ranking) values (186, 'Garota Exemplar (2014)', '8.1');
INSERT INTO movie (id, title, ranking) values (187, 'Harry Potter e as Relíquias da Morte - Parte 2 (2011)', '8.1');
INSERT INTO movie (id, title, ranking) values (188, 'O Franco Atirador (1978)', '8.1');
INSERT INTO movie (id, title, ranking) values (189, 'Em Nome do Pai (1993)', '8.1');
INSERT INTO movie (id, title, ranking) values (190, 'O Grande Hotel Budapeste (2014)', '8.1');
INSERT INTO movie (id, title, ranking) values (191, 'A Mulher Faz o Homem (1939)', '8.1');
INSERT INTO movie (id, title, ranking) values (192, 'Barry Lyndon (1975)', '8.1');
INSERT INTO movie (id, title, ranking) values (193, 'O Salário do Medo (1953)', '8.1');
INSERT INTO movie (id, title, ranking) values (194, 'Bancando o Águia (1924)', '8.1');
INSERT INTO movie (id, title, ranking) values (195, 'Memórias de um Assassino (2003)', '8.1');
INSERT INTO movie (id, title, ranking) values (196, 'Até o Último Homem (2016)', '8.1');
INSERT INTO movie (id, title, ranking) values (197, 'Klaus (2019)', '8.1');
INSERT INTO movie (id, title, ranking) values (198, 'Relatos Selvagens (2014)', '8.1');
INSERT INTO movie (id, title, ranking) values (199, 'O Sétimo Selo (1957)', '8.1');
INSERT INTO movie (id, title, ranking) values (200, 'O Quarto de Jack (2015)', '8.1');
INSERT INTO movie (id, title, ranking) values (201, 'Mad Max: Estrada da Fúria (2015)', '8.1');
INSERT INTO movie (id, title, ranking) values (202, 'Como Treinar o Seu Dragão (2010)', '8.1');
INSERT INTO movie (id, title, ranking) values (203, 'O Grande Lebowski (1998)', '8.1');
INSERT INTO movie (id, title, ranking) values (204, 'Mary e Max: Uma Amizade Diferente (2009)', '8.1');
INSERT INTO movie (id, title, ranking) values (205, 'Monstros S.A. (2001)', '8.1');
INSERT INTO movie (id, title, ranking) values (206, 'Tubarão (1975)', '8.1');
INSERT INTO movie (id, title, ranking) values (207, 'O Martírio de Joana DArc (1928)', '8.1');
INSERT INTO movie (id, title, ranking) values (208, 'Era uma Vez em Tóquio (1953)', '8.1');
INSERT INTO movie (id, title, ranking) values (209, 'Sociedade dos Poetas Mortos (1989)', '8.1');
INSERT INTO movie (id, title, ranking) values (210, 'Hotel Ruanda (2004)', '8.1');
INSERT INTO movie (id, title, ranking) values (211, 'Rocky: Um Lutador (1976)', '8.0');
INSERT INTO movie (id, title, ranking) values (212, 'Ford vs Ferrari (2019)', '8.0');
INSERT INTO movie (id, title, ranking) values (213, 'Platoon (1986)', '8.0');
INSERT INTO movie (id, title, ranking) values (214, 'A Canção da Estrada (1955)', '8.0');
INSERT INTO movie (id, title, ranking) values (215, 'Conta Comigo (1986)', '8.0');
INSERT INTO movie (id, title, ranking) values (216, 'O Exterminador do Futuro (1984)', '8.0');
INSERT INTO movie (id, title, ranking) values (217, 'Spotlight: Segredos Revelados (2015)', '8.0');
INSERT INTO movie (id, title, ranking) values (218, 'Rush: No Limite da Emoção (2013)', '8.0');
INSERT INTO movie (id, title, ranking) values (219, 'Logan (2017)', '8.0');
INSERT INTO movie (id, title, ranking) values (220, 'Rede de Intrigas (1976)', '8.0');
INSERT INTO movie (id, title, ranking) values (221, 'Na Natureza Selvagem (2007)', '8.0');
INSERT INTO movie (id, title, ranking) values (222, 'O Mágico de Oz (1939)', '8.0');
INSERT INTO movie (id, title, ranking) values (223, 'Ratatouille (2007)', '8.0');
INSERT INTO movie (id, title, ranking) values (224, 'Feitiço do Tempo (1993)', '8.0');
INSERT INTO movie (id, title, ranking) values (225, 'Antes do Pôr-do-Sol (2004)', '8.0');
INSERT INTO movie (id, title, ranking) values (226, 'O Exorcista (1973)', '8.0');
INSERT INTO movie (id, title, ranking) values (227, 'Os Melhores Anos de Nossa Vida (1946)', '8.0');
INSERT INTO movie (id, title, ranking) values (228, 'Os Incríveis (2004)', '8.0');
INSERT INTO movie (id, title, ranking) values (229, 'Ser ou Não Ser (1942)', '8.0');
INSERT INTO movie (id, title, ranking) values (230, 'As Vinhas da Ira (1940)', '8.0');
INSERT INTO movie (id, title, ranking) values (231, 'A Batalha de Argel (1966)', '8.0');
INSERT INTO movie (id, title, ranking) values (232, 'Rebecca, a Mulher Inesquecível (1940)', '8.0');
INSERT INTO movie (id, title, ranking) values (233, 'Sempre ao Seu Lado (2009)', '8.0');
INSERT INTO movie (id, title, ranking) values (234, 'Rebeldia Indomável (1967)', '8.0');
INSERT INTO movie (id, title, ranking) values (235, 'Amores Brutos (2000)', '8.0');
INSERT INTO movie (id, title, ranking) values (236, 'Piratas do Caribe: A Maldição do Pérola Negra (2003)', '8.0');
INSERT INTO movie (id, title, ranking) values (237, 'O Ódio (1995)', '8.0');
INSERT INTO movie (id, title, ranking) values (238, 'Os Incompreendidos (1959)', '8.0');
INSERT INTO movie (id, title, ranking) values (239, 'Meu Pai e Meu Filho (2005)', '8.0');
INSERT INTO movie (id, title, ranking) values (240, 'Quando Duas Mulheres Pecam (1966)', '8.0');
INSERT INTO movie (id, title, ranking) values (241, 'Aconteceu Naquela Noite (1934)', '8.0');
INSERT INTO movie (id, title, ranking) values (242, 'A Vida de Brian (1979)', '8.0');
INSERT INTO movie (id, title, ranking) values (243, 'A Noviça Rebelde (1965)', '8.0');
INSERT INTO movie (id, title, ranking) values (244, 'Dersu Uzala (1975)', '8.0');
INSERT INTO movie (id, title, ranking) values (245, 'A Criada (2016)', '8.0');
INSERT INTO movie (id, title, ranking) values (246, 'Jai Bhim (2021)', '8.0');
INSERT INTO movie (id, title, ranking) values (247, 'Aladdin (1992)', '8.0');
INSERT INTO movie (id, title, ranking) values (248, 'Gandhi (1982)', '8.0');
INSERT INTO movie (id, title, ranking) values (249, 'Histórias Cruzadas (2011)', '8.0');
INSERT INTO movie (id, title, ranking) values (250, 'O Gigante de Ferro (1999)', '8.0');